### ISSUE TITLE
Idea: Having separate GIFs for LSTM and RIMs

### ISSUE THREAD

**Issue by alexmlamb** [dido1998/Recurrent-Independent-Mechanisms#1]
Hello, 

I think it would be neat to have side-by-side gifs (on minigrid) for LSTM and RIMs.  This would make the difference more intuitive.  

Best, 

Alex.

**Comment by dido1998** [comment]
Hi @alexmlamb , Thanks for the suggestion! I will add them ASAP.

**Comment by dido1998** [comment]
Hi @alexmlamb , I have added the side-by-side gifs.
