### ISSUE TITLE
quick corrections on api document

### ISSUE THREAD

**Issue by wwu** [dido1998/Recurrent-Independent-Mechanisms#4]
in RIM output document, it says:

Output | Description
-- | --
output | Output of shape (seq_len, batch_size, num_directions * hidden_size)

I guess the last dimension should be num_units*num_directions*hidden_size? 

Good work by the way, thanks for sharing this.

**Comment by dido1998** [comment]
Hi, Thanks for pointing this! I will make the changes.

**Comment by dido1998** [comment]
Done.
